[package]
name = "rustc_parse_format"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc-literal-escaper = "0.0.2"
rustc_lexer = { path = "../rustc_lexer" }
# tidy-alphabetical-end

